export const ARTIST_KEYS = [
  "artist_bish",
  "artist_bis",
  "artist_zoc",
  "artist_gang_parade",
  "artist_empire",
  "artist_exwhyz",
  "artist_carry_loose",
  "artist_sgo",
  "artist_yurumerumo",
  "artist_passcode",
  "artist_zenkisei",
  "artist_niji_con",
  "artist_dempagumi",
  "artist_migma_shelter",
  "artist_frui_tear",
  "artist_brats",
  "artist_prismil",
  "artist_malcolm_mask",
  "artist_necronomidol",
  "artist_lyrical_school",
  "artist_predia",
  "artist_candye_syrup",
  "artist_babymetal",
  "artist_deviloof",
  "artist_tip",
  "artist_upupgirls",
  "artist_shiritsu",
  "artist_sakurazaka",
  "artist_hinatazaka",
  "artist_nogizaka",
  "artist_akb48",
] as const;

export type ArtistKey = (typeof ARTIST_KEYS)[number];
